/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      'xs': '480px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed": "#e2dfff",
        "outline-variant": "#c7c4d8",
        "on-secondary-container": "#5c647a",
        "on-tertiary-container": "#ffd2be",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "secondary": "#565e74",
        "on-secondary-fixed": "#131b2e",
        "surface-tint": "#4d44e3",
        "on-tertiary-fixed": "#351000",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "tertiary": "#7e3000",
        "primary": "#3525cd",
        "inverse-on-surface": "#eff1f3",
        "error-container": "#ffdad6",
        "inverse-primary": "#c3c0ff",
        "on-surface-variant": "#464555",
        "surface-dim": "#d8dadc",
        "tertiary-fixed": "#ffdbcc",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f6",
        "outline": "#777587",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#0f0069",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-container": "#4f46e5",
        "surface": "#f7f9fb",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "tertiary-container": "#a44100",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
